name: mssm
channels:
  - defaults
dependencies:
  - ca-certificates=2021.9.30=hecd8cb5_1
  - certifi=2021.5.30=py39hecd8cb5_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1l=h9ed2024_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.7=h88f2d9e_1
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py39hecd8cb5_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.11=h7bc2e8c_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - attrs==21.4.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - chex==0.1.0
    - cloudpickle==2.0.0
    - corner==2.2.1
    - cycler==0.11.0
    - dill==0.3.4
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - flax==0.3.6
    - fonttools==4.28.5
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.4.0
    - gin-config==0.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - gym==0.21.0
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==4.10.0
    - jax==0.2.26
    - jaxlib==0.1.75
    - joblib==1.1.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==12.0.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - msgpack==1.0.3
    - numpy==1.22.0
    - numpyro==0.8.0
    - opt-einsum==3.3.0
    - optax==0.1.0
    - packaging==21.3
    - pillow==9.0.0
    - promise==2.3
    - protobuf==4.0.0rc2
    - psutil==5.9.0
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - requests==2.27.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - sklearn==0.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.7.0
    - tensorflow-datasets==4.4.0
    - tensorflow-estimator==2.7.0
    - tensorflow-hub==0.12.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-metadata==1.5.0
    - tensorflow-text==2.7.3
    - threadpoolctl==3.0.0
    - toolz==0.11.2
    - torch==1.10.1
    - tqdm==4.62.3
    - trax==1.4.1
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
